name: CD

on:
  push:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Docker image
        run: docker pull karthikmehrotra/test:latest

      - name: Start Docker container
        id: run-container
        run: |
          container_id=$(docker run -d -p 8080:8080 karthikmehrotra/test:latest)
          echo "::set-output name=container_id::$container_id"
          docker ps 
     
#       - name: Copy logs from container
#         run: docker cp ${{ steps.run-container.outputs.container_id }}:/app/logs.txt logs.txt
