name: CD

on:
  push:
    branches:
      - trigger-workflow

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Docker image
        run: docker pull karthikmehrotra/test:5311263057

      - name: Start Docker container
        run: |
          container_id=$(docker run -d -p 8080:8080 karthikmehrotra/test:5311263057)
          sleep 10
          docker ps

      - name: Check container logs
        run: docker logs $container_id
