name: CD

on:
  push:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Docker image
        run: docker pull karthikmehrotra/test:5311263057

      - name: Start Docker container
        id: run-container
        run: |
          container_id=$(docker run -d -p 8080:8080 -v $PWD/E-commerce-project-springBoot-master2/JtProject/target:/app karthikmehrotra/test:5311263057)
          echo "::set-output name=container_id::$container_id"
          sleep 10
          docker ps
     
      - name: Copy logs from container
        run: docker cp ${{ steps.run-container.outputs.container_id }}:/app/logs.txt logs.txt
