name: CD

on:
  push:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Docker image
        run: docker pull karthikmehrotra/test:latest

      - name: Start Docker container
        id: run-container
        run: |
          container_id=$(docker run -d -p 8080:8080 karthikmehrotra/test:latest)
          echo "::set-output name=container_id::$container_id"
          docker ps 
          
      - name: Check JAR file in Docker container
        run: |
           container_id=$(docker ps -q)  # Get the container ID
           docker exec $container_id find /app -name "JtSpringProject-0.0.1-SNAPSHOT.jar"
           
      - name: Get Container IP address
        id: get-container-ip
        run: |
          container_id=$(echo ${{ steps.run-container.outputs.container_id }})
          container_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $container_id)
          echo "::set-output name=container_ip::$container_ip"
     
#       - name: Copy logs from container
#         run: docker cp ${{ steps.run-container.outputs.container_id }}:/app/logs.txt logs.txt
