name: CI

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install maven -y

      - name: Navigate to JtProject directory
        run: cd E-commerce-project-springBoot-master2/JtProject

      - name: Build with Maven
        run: |
          cd E-commerce-project-springBoot-master2/JtProject
          mvn package -DskipTests=true
      - name: Find JAR file
        id: find-jar
        run: |
            jar_file=$(find E-commerce-project-springBoot-master2/JtProject/target -name "*.jar")
            echo "::set-output name=jar_file::$jar_file"


      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file E-commerce-project-springBoot-master2/JtProject/DockerFile --tag ${{ secrets.DOCKERHUB_USERNAME }}/test:${{ github.run_id }}

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/test:${{ github.run_id }}

 
