name: Master Workflow

on:
  push:
    branches:
      - master

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install maven -y
      - name: Navigate to JtProject directory
        run: cd E-commerce-project-springBoot-master2/JtProject

      - name: Build with Maven
        run: |
          cd E-commerce-project-springBoot-master2/JtProject
          mvn package -DskipTests=true
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file E-commerce-project-springBoot-master2/JtProject/DockerFile --tag ${{ secrets.DOCKERHUB_USERNAME }}/test:${{ github.run_id }}

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/test:${{ github.run_id }}
        
      - uses: ./ci.yml
      
  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Fetch Docker image
        run: docker pull karthikmehrotra/test:5311263057

      - name: Start Docker container
        id: run-container
        run: |
          container_id=$(docker run -d -p 8080:8080 karthikmehrotra/test:5311263057)
          echo "::set-output name=container_id::$container_id"
          sleep 10
          docker ps
